---
- name: Deploy XMPP stack
  hosts: xmpp_hosts
  become: true
  roles:
    - role: common
    - role: firewall
    - role: dns
    - role: postgres
    - role: ejabberd
    - role: coturn
    - role: nginx
      when: xmpp_stack_enable_nginx | bool
    - role: certbot
